### ISSUE TITLE
New Tasks are saved minus/plus 1 day

### ISSUE THREAD

**Issue by iammac2** [AllediaWordPress/UpStream#469]
Seen on UpStream 1.17.0

* Created new task
* We entered start day of 07/05/18 and end day of 07/05/18
* Save new task
* Task is displayed on project as 06/05/18
* Click task on calendar and the date is 06/05/18

Our time zone is London

See attached 

![4bf22fee-1c67-4888-86ef-3f082c939915](https://user-images.githubusercontent.com/38664343/39661208-d3698496-5045-11e8-8f85-e232ad92121f.png)
![08ce558e-bb6a-4cd6-8d5e-5761a70c9a20](https://user-images.githubusercontent.com/38664343/39661209-d38ceb20-5045-11e8-9576-06a547ee9f96.png)
![434c214c-352b-47a5-9522-0d8c2f62da59](https://user-images.githubusercontent.com/38664343/39661210-d3a7e1aa-5045-11e8-935a-9f6f5814e25a.jpeg)

**Comment by iammac2** [comment]
Also notifications.....
![5feeb966-b261-48ca-9a6e-b178eaafdc5b](https://user-images.githubusercontent.com/38664343/39661759-e1ed7fd2-504e-11e8-80bb-5b388932c6d5.jpeg)

**Comment by stevejburge** [comment]
Related bug: https://github.com/upstreamplugin/UpStream/issues/411

**Comment by stevejburge** [comment]
Suggestion from Ian:

> The date to save being set in MySQL from UI should be unchanged - if it does change once in the DB then the DB schema must be at fault in some way, maybe not be using UTC?

This is definitely a problem that happens inconsistently, and only on European-based servers, so it's a good suggestion

**Comment by iammac2** [comment]
Sure. Just means we can't create any tasks yet.

**Comment by stevejburge** [comment]
Thanks Ian. We're on it.

**Comment by iammac2** [comment]
Any eta yet on this? Thanks

**Comment by stevejburge** [comment]
Hi @iammac2 We definitely plan to take a look at it this week. We've had no more reports of this, so it's likely an unusual configuration with your db or server.

**Comment by iammac2** [comment]
Hi @stevejburge - I think you mentioned #411 there had been 3 reports. We have now tested an alternate solution with calendar view that is working for us. Since we need to have an solution ready to go we will switch over to use the alternative product. We would therefgore like to cancel our licence & obtain a refund. Sorry it didn't work out for us, otherwise we thought your product had a lot to offer.

**Comment by stevejburge** [comment]
Hi @iammac2 Sorry, we are working on a fix and hope to have it testable today.

Please don't post account questions on Github. Our support team can help there.

**Comment by andergmartins** [comment]
Hi @iammac2 I think I have fixed it. Please, could you check the attached packages?

[upstream.1.17.1.beta.1.zip](https://github.com/AllediaWordPress/UpStream/files/2014329/upstream.1.17.1.beta.1.zip)
[upstream-calendar-view-1.0.9.beta.1.zip](https://github.com/AllediaWordPress/UpStream/files/2014333/upstream-calendar-view-1.0.9.beta.1.zip)

Please, let us know if it fixes the issue, or if you still have any other issue.
Looking forward to helping.

**Comment by iammac2** [comment]
Thank you. I uninstalled the official versions and installed the zips. Had a few mins to test. Couldn’t see a difference though

**Comment by andergmartins** [comment]
Thanks, I was making more tests and I can reproduce this but with the date plus 1 day. Seems to be related to a combination between the timezone setting on WP, PHP, and MySQL, plus the date format. 

@iammac2 please, could you let me know what timezone you have set for PHP, MySQL and WordPress? What Date format you are using on WP?

**Comment by andergmartins** [comment]
@iammac2 please, could you try these packages?
Since I can't reproduce the issue locally it is hard to double check the fix.

[upstream-email-notifications-v1.1.10-beta.1.zip](https://github.com/AllediaWordPress/UpStream/files/2115813/upstream-email-notifications-v1.1.10-beta.1.zip)

[upstream-v1.18.3-beta.1.zip](https://github.com/AllediaWordPress/UpStream/files/2115829/upstream-v1.18.3-beta.1.zip)

[upstream-frontend-edit-v1.6.3-beta.1.zip](https://github.com/AllediaWordPress/UpStream/files/2115835/upstream-frontend-edit-v1.6.3-beta.1.zip)

I know you are using London as timezone, but is it the same for WP, PHP, and MySQL? If not, what is the setting for each one? I tried different combinations of settings but wasn't able to reproduce the issue.

**Comment by b-trav** [comment]
I can currently reproduce the exact bug described in this issue.
My server is located in the US (Amazon server), but the timezone is set Perth, Australia time.
```
date
```
on the server returns:
```
Thu Jun 28 11:25:18 AWST 2018
```
WordPress is set to UTC+8
```
 Universal time (GMT) is 2018-06-28 03:26:18. Local time is 2018-06-28 11:26:18. 
```
```
php> echo date('H:i:s');
```
returns
```
11:28:14
```
As for MySQL, I get
```
mysql> select now();
+---------------------+
| now()               |
+---------------------+
| 2018-06-28 11:31:08 |
+---------------------+
1 row in set (0.00 sec)
```
So they all appear to match.

**Comment by stevejburge** [comment]
Thansk @b-trav Is this still a problem with the latest release of UpStream, version 1.18.4?

**Comment by b-trav** [comment]
Hi, yes, I am running version 1.18.4, and the bug is reproducible - see the two images below. The first image is creating a task and setting start and end date as today. The second image is after clicking on the edit task icon.
I don't think it can be a timezone thing because it is pretty much 28 June everywhere in the world now (expect maybe Hawaii)
![test_task1](https://user-images.githubusercontent.com/16848340/42038321-423122ce-7b1d-11e8-9f57-6d35179746d6.png)
![test_task2](https://user-images.githubusercontent.com/16848340/42038338-4908cd5e-7b1d-11e8-81da-ecfc9618dcd9.png)

**Comment by EdmOst** [comment]
The same issue - not only for tasks also for milestones. 
Example. If you set in calendar 18/07/2018 it saves 17/07/2018 and says the date is invalid also if you reopen
